"""empty message

Revision ID: 087d83f43bf5
Revises: d53d3f23bcfa
Create Date: 2021-08-07 09:16:49.219362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '087d83f43bf5'
down_revision = 'd53d3f23bcfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('ref', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votes', 'ref')
    # ### end Alembic commands ###
