"""empty message

Revision ID: 2794aff57bf4
Revises: 087d83f43bf5
Create Date: 2021-08-07 10:03:01.177990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2794aff57bf4'
down_revision = '087d83f43bf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votes', 'name')
    # ### end Alembic commands ###
