"""empty message

Revision ID: 774ec40dcb2a
Revises: 567b865a1862
Create Date: 2021-07-11 21:43:56.651719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '774ec40dcb2a'
down_revision = '567b865a1862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'votes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('votes', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
