"""empty message

Revision ID: d53d3f23bcfa
Revises: 26440417d953
Create Date: 2021-08-06 11:51:19.459607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd53d3f23bcfa'
down_revision = '26440417d953'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('updatedVotes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'updatedVotes')
    # ### end Alembic commands ###
